app:
  build: .
  links:
   - db
  ports:
   - "1234:1234" # change to whatever port is to be used
  environment:
   - NODE_ENV=development # production for staging
db:
  image: mongo
  ports:
   - "12345:12345"